In [40]:
import numpy as np
import pandas as pd

In [41]:
df = pd.read_csv('Californiahousing.csv.txt')
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [42]:
#Question-2 How many columns are in the dataset?
df.shape
#answer 10

(20640, 10)

In [43]:
#Question-3 Which columns in the dataset have missing values?

df.isna().sum()
#answer total_bedrooms column has 207 null values

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [44]:
#Question 4 How many unique values does the ocean_proximity column have?
df['ocean_proximity'].unique()
#answer 5

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [45]:
#Question 5 What's the average value of hte median_house_value for the houses located near the bay?
mean_near_bay = df[df['ocean_proximity']=='NEAR BAY']['median_house_value'].mean()
round(mean_near_bay,0)
#answer 259212

259212.0

In [53]:
#Question 6 
#a)Calculate the average of the total_bedrooms column in the dataset
avg_total_bedrooms = round(df['total_bedrooms'].mean(),3)
#answer 538
avg_total_bedrooms

537.872

In [54]:
#6b Use fillna method to fill the missing values in the total_bedrooms with the mean value from the previous step
#df.isna().sum()
#df['total_bedrooms'].isna().sum()
df['total_bedrooms'].fillna(avg_total_bedrooms, inplace = True)

In [55]:
df.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [56]:
round(df['total_bedrooms'].mean(),3)
#no the mean has not changed after imputation

537.872

In [57]:
pd.__version__

'1.4.4'

In [58]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [65]:
x = df[df['ocean_proximity']=='ISLAND'][['housing_median_age','total_rooms','total_bedrooms']].values

In [66]:
x

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [69]:
xTx = np.dot(x.T, x)

In [74]:
inv_xTx = np.linalg.inv(xTx)

In [72]:
y = np.array([950,1300,800,1000,1300])

In [73]:
y

array([ 950, 1300,  800, 1000, 1300])

In [78]:
w = np.dot(inv_xTx,x.T) * y

In [79]:
w

array([[-7.84328036, -8.49171012, -1.85727372, 25.65143741, 15.6641364 ],
       [-1.57559761,  1.44833145,  1.11724729, -1.03214974, -1.43907321],
       [ 7.16646682, -3.92552691, -3.64100058,  1.81685089,  4.28243922]])